engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
exclude_paths:
- "*.md"
- "*.json"
- "/test/**/*"
- karma.conf.js
- index.js
- gulpfile.js
