language: node_js
node_js:
- 4.2.1
sudo: false
env:
  global:
  - secure: PKoZxdUSCUgiNCCcocezhvRAFv2bB4Zshfp2RqWC1WtnKcFh+UKueMMDHhk5FTzfioXA32rVOcma1fvEoocai6kQi0kpwhkPLK46IONJGKaPMMSBsbgrocR1jouXLmnygz19JkdiXjwlmERQb6dLlCIJ/LZ/VesqwFJARQzFljk7MXRoXLcn4XvWE1KTcjFjA2ySGzzfVpbBlqeDm7ss18/Pw27LJUDMsi2h9W/pJq4XAsAJuGTQI5mQLYv0r4u/yRP2VAGts6+VbGArKWB8gEPDlaLGX0htCxnhbra1sm90HZJqv/+EQ6ayRH7ktrkJuKAWygilLcqOWMzQdNVyHOtzufbGvVDjkgKGotLr8C6DZxx9Ktn7TwyM0N2uvlhxHCPr0C4OxyqNRXg1ICCUG4rVcZx2ZzNbPiulO6OJpi94vmdJg+Y0nTYL0gNDbEsR/MrrflIy4fedng4xVV3r59m2jKbMosIiY9+FWzoZmxijYgRriOn7fjy/WexP1Dvh7xAhHT67LjVjAPEVCwdu394gcKHSr2JhfIRCK9REfrJSKYunKcmlCoN1zXuqwSbJCzPEf9LefKUyhv1rqDQrCAiR/nbsgd6xWLPCker7ss+mHizZ1QVlbmH0CSO3HttbxAw5uVUEc39G1oxjxnfvOL/x5ClVtwdtroP0mednajg=
  - secure: vv/UdQ3aImh8iorFsZZg3P2uTdfoSceVB6AM648P025DfF823Kw9iOe9/K3iF46Td1nbmdgFvTlP4tP70UizAa6pSSxmlzbpdU0MTXzLl+LFFIcr2OBaPnKold0PRLQOjybCmXJZg/2sOxJp9Bzwu51PF9v4V8XZLQAHDPcTkVPOvKOic09xV240aWmhGZkGD47UPjBvRd8BFVS7ZxRX9m3rWktDwDXcegW4a1iQfqnPVa78xurDCSjJFkt0HJI/de9M5H4dcR0qgPxJkLEtaKwA2rbNbAfXfC8Wvoe15yuW5ByE1m2O/XP8F5unBiEe9nAguns5+qnN/cID5zGd7q7Zgh6CphRaBe9WmjZCml7PKSDNK+xS4znfc2ap+8WSlX9+3n4uiahtDwuoWv0WHZO8LfEQY1Jv1me4D8vKkbJBYRpKLab7pzXGWgThj5p/0a1bjtux/M/USypSstnZwMFn6aWYccKYZVnGxH8b3aeKgvW6DNc4m81RN+EcTJ+2IkRv2gtOqOUDj1yJ3GhRauqUFIUg6fFIUw286slpr76LUrc05XZ4u3dyYl8yIu8LrnF1Oqbz98gf0hgfkdygl/emXq08n2b8vL3av/ncq/k3ju6RUY1+bZnlKWfD/AdwDsbnTIbI3k7W3OldYMfhHpwZIm6I7dP4H0lUxxHHobg=

addons:
  sauce_connect: true
  apt:
    packages:
    - make
    - time

before_script:
  - npm install -g gulp

before_deploy: gulp build

deploy:
  provider: releases
  api_key:
    secure: UEZO7sdpTHikoN2y4gKXlARIlUkboV+Rt1+NgpDGD5aX5y59rFKowQZdMzGjOFo3fVL8r7EABywxJrtiN2CPur/srfKHKJgipUUl+Rq0J3NEuUl39XCrEEfefavP6ofVYv6gUeUELJcK6SX+Bpu6h6YDZMTz1x/mymdKRYV4fgDtWwQU5f2BJKeU3Fg+GcvSINnn+zUfoWqIEh+n3NhbclHuji6k6mEfKZA2cZwh+88oVU5O91DbYBBqXsR/KAj1y3AbdU7r8ZAMlxpwetj/p+SXbEfUwZk3b3ZKCQKNutEI+lbhAewPeQaTJAcCj1gU+bM8K+7lG2H6rfwH35Xq1pGsHgLd9ouUYxt9SmD84ox76+hWxueKrGATPfo7HFBCV6aAOsEdLoWBTY3GkVuSqr6Fu7LsFq3M4+exxct+yb8TLNog5ZkqSZ2/R3gJf5oJT/x4AoFZjn2x3Pc6l5b/EC2q7Q4PGQxLkvEeQdtWGqOHVytR6j5YVf7tedwj6K5KOhvtwvKInxa4wy9puWaTkoVtZKp5X1i10da5exDUWPxCouL/BT0cNVHuAs12k3yR+ta8chGxokHEx+k6ipn3pXDAUfAPCmEiIRA8AgqwPGwScynEUn6yPGNYP2AJC7GfRzy1YGDyhvYpgqyg55QIr9dv4SChSVoOgqdeAiS2uvc=
  file:
    - dist/chassis.min.js
    - dist/chassis.slim.min.js
    - dist/chassis.dev.js
    - dist/ngn.min.js
    - dist/bus.min.js
    - dist/dom.min.js
    - dist/http.min.js
    - dist/reference.min.js
    - dist/svg.min.js
    - dist/data.model.min.js
    - dist/data.store.min.js
    - dist/data.proxy.min.js
    - bower.json
  skip_cleanup: true
  on:
    tags: true

cache:
  directories:
    - node_modules
