language: node_js

node_js:
- '4.2.1'

sudo: false

env:
  global:
    - secure: PKoZxdUSCUgiNCCcocezhvRAFv2bB4Zshfp2RqWC1WtnKcFh+UKueMMDHhk5FTzfioXA32rVOcma1fvEoocai6kQi0kpwhkPLK46IONJGKaPMMSBsbgrocR1jouXLmnygz19JkdiXjwlmERQb6dLlCIJ/LZ/VesqwFJARQzFljk7MXRoXLcn4XvWE1KTcjFjA2ySGzzfVpbBlqeDm7ss18/Pw27LJUDMsi2h9W/pJq4XAsAJuGTQI5mQLYv0r4u/yRP2VAGts6+VbGArKWB8gEPDlaLGX0htCxnhbra1sm90HZJqv/+EQ6ayRH7ktrkJuKAWygilLcqOWMzQdNVyHOtzufbGvVDjkgKGotLr8C6DZxx9Ktn7TwyM0N2uvlhxHCPr0C4OxyqNRXg1ICCUG4rVcZx2ZzNbPiulO6OJpi94vmdJg+Y0nTYL0gNDbEsR/MrrflIy4fedng4xVV3r59m2jKbMosIiY9+FWzoZmxijYgRriOn7fjy/WexP1Dvh7xAhHT67LjVjAPEVCwdu394gcKHSr2JhfIRCK9REfrJSKYunKcmlCoN1zXuqwSbJCzPEf9LefKUyhv1rqDQrCAiR/nbsgd6xWLPCker7ss+mHizZ1QVlbmH0CSO3HttbxAw5uVUEc39G1oxjxnfvOL/x5ClVtwdtroP0mednajg=
    - secure: vv/UdQ3aImh8iorFsZZg3P2uTdfoSceVB6AM648P025DfF823Kw9iOe9/K3iF46Td1nbmdgFvTlP4tP70UizAa6pSSxmlzbpdU0MTXzLl+LFFIcr2OBaPnKold0PRLQOjybCmXJZg/2sOxJp9Bzwu51PF9v4V8XZLQAHDPcTkVPOvKOic09xV240aWmhGZkGD47UPjBvRd8BFVS7ZxRX9m3rWktDwDXcegW4a1iQfqnPVa78xurDCSjJFkt0HJI/de9M5H4dcR0qgPxJkLEtaKwA2rbNbAfXfC8Wvoe15yuW5ByE1m2O/XP8F5unBiEe9nAguns5+qnN/cID5zGd7q7Zgh6CphRaBe9WmjZCml7PKSDNK+xS4znfc2ap+8WSlX9+3n4uiahtDwuoWv0WHZO8LfEQY1Jv1me4D8vKkbJBYRpKLab7pzXGWgThj5p/0a1bjtux/M/USypSstnZwMFn6aWYccKYZVnGxH8b3aeKgvW6DNc4m81RN+EcTJ+2IkRv2gtOqOUDj1yJ3GhRauqUFIUg6fFIUw286slpr76LUrc05XZ4u3dyYl8yIu8LrnF1Oqbz98gf0hgfkdygl/emXq08n2b8vL3av/ncq/k3ju6RUY1+bZnlKWfD/AdwDsbnTIbI3k7W3OldYMfhHpwZIm6I7dP4H0lUxxHHobg=

notifications:
  hipchat:
    rooms:
      secure: G86agoGJWFpnW+DIwoY0iZjTi4858qgZUnVSFKkz39zfeIFm/lnmcBG3MqLMzvkjFrj+qoofqAUUbycvA8ZE7FbX6+rOfChPpco14LM/cPWrltNuLEYGHA5ikLTrGXOQpy6HFx0MFxhDQc5GFZWoNOVZb8bRogyv1PZwS2AG7tQ=
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    format: html

addons:
  sauce_connect: true