language: node_js
node_js:
- '4.2.1'
sudo: false
env:
  global:
    - secure: yZtwIzjDLWrprDrZKtc7lVw9LsfWRogK1sixIXGrYm59iUWTCd+3/2BhXexppwVfE9KJjorIDQxOFT9YdDQT6hQ5OhvSJs2O6c7SzkqRJLGIg4rwK3XoRG7jGhnPu2X8Dl9gBHqDkP3sMzIoz3X4e1UHRFUJosjS4m+9b4iS7XImS7zkwPezIY3/MIo/thFfEs1hui4j5TBLJ3OgZf7WR+hsYwOqWO1Tc840cc6bPQ7AJ41RYN0lc1AhQIs5bx7N//VpHhtl7PKaXZhQ/HZU45qcpAC1okfpJzEw477j7CLaULcsNdGgm4cvAdWRZ9RhXpeBRjiwz5DbOTnUKD8uY5lgvdcLDKmUVNaE76ntYgPsCA4bPoW1eerxEsCPWh6bdu5oF+UfxfdVs2rjUamGHiXwsG9/gtiLoTlAKJUkdctiA1DupCX0UF0eHSureHLLGksanyaSUTpCkSkTZgO9orLGJxIBZ43KbSkPMCVzALn/wcqLTWzv2a1y8T2Wf9Tyb1BLoeGQGx4lF9QhBC6MqaC8nmzncJS9HINufTTDM1oVHA3fku6ktKpOE+Jn+2a+cuhN7Yguk//sS5BlKK9FsdtdXibYJ0w1ACCkP1AIah3Tg2iokzp8GbhxeR9U1lsoLtLma3kNPNxyDvqndbr6xIXTEDEzcGszHxbRr65vWxI=
    - secure: Zk5wE/kEcwh6+65r9NcjV8tUjtGTRqAxb/fBeZUqHBFzBUEZ6sgoCwiQugQWWIUpCtIdSvl7Xk2jJdevcj8PL5sgk4Q4aleZAOFe05A6j8fXDB293W7WRN193WOL8EdVLFwEbvVWCjr6CoxyVcSpCBmUITcp0/Arp/mXsEUIfIvdyIrQwqPhxKw4iJd5ISgDRySCU1QLJH9IH7YeqtrhGU6bIUFXoLWPb4u4P+m9v0IYSxSu9NNBm4csupdY6HINxFQMy65F54XGHjhS7L9y+xOb8sizCchcPkpfYuFm7mk0FBTSUqZ9M7ng/uFAzIe40u8gy+YdcaWBKA/Obpq2SU/2pZGJGKV83c+xKogjwJCdShH5TqyWz1OyplLJHZ1MndqoyFF6cEWzitDO23RdbAL6LgupCdXEmFoleKlKwqWEnzA/558bDL+bITV+HoQ8AxTHwvmtskz2Z8xOXYYfZYGGFiYl66S+BolD9vnFke1rBDUMQzWXxwlaVIw9oDlRa5QMMmhjoL2PG+ExhUIJ60M68LyPAi3BHjJanIzYkGapRXjr1L6UvXvtd0LpeZFEM2kfEd+Av82MNWJKItJDMeEtDF6WGTcQo/UxW69ofyBU3JjZ65MZ0lFoSUO1k0zzbR0854OJlFdPHvVfpmYiybd6wHYhDugJmj6Yc8O9qFk=
notifications:
  hipchat:
    rooms:
      secure: G86agoGJWFpnW+DIwoY0iZjTi4858qgZUnVSFKkz39zfeIFm/lnmcBG3MqLMzvkjFrj+qoofqAUUbycvA8ZE7FbX6+rOfChPpco14LM/cPWrltNuLEYGHA5ikLTrGXOQpy6HFx0MFxhDQc5GFZWoNOVZb8bRogyv1PZwS2AG7tQ=
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    format: html

addons:
  sauce_connect: true